name: Deploy Django to EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Deploy to EC2
        run: |
          aws ssm send-command \
            --instance-ids "i-06c2710555d918074" \
            --document-name "SSM-SessionManagerRunShell" \
            --comment "Updating Django application" \
            --parameters commands=[
                "set -e",

                "# 1. Pull latest code on EC2",
                "cd /home/ubuntu/django",
                "git pull origin main",

                "# 2. Update dependencies on EC2",
                "pipenv install -r requirements.txt",

                "# 3. Update .env from S3 on EC2",
                "aws s3 cp s3://hellokorea-test-zone/prod_web_env/.env.production /home/ubuntu/django/hellokorea/.env.production",

                "# 4. Update Django migrations & Check RDS online status on EC2",
                "pipenv shell",
                "cd /home/ubuntu/django/hellokorea",
                "python manage.py makemigrations",
                "MIGRATE_OUTPUT=$(python manage.py migrate 2>&1)",
                "echo \"$MIGRATE_OUTPUT\"",
                "[[ \"$MIGRATE_OUTPUT\" == *'Running migrations'* && \"$MIGRATE_OUTPUT\" != *'UnicodeDecodeError'* && \"$MIGRATE_OUTPUT\" != *'MigrationSchemaMissing'* ]] || { echo 'Migration failed'; exit 1; }",
                
                "# 5. Recollect statics on EC2",
                "python manage.py collectstatic --noinput",

                "# 6. Restart Gunicorn on EC2",
                "exit",
                "sudo systemctl restart gunicorn",
            ] \
            --timeout-seconds 600
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
